updated All

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -84,28 +84,28 @@ jobs:
       - name: Show python test results log
         run: cat python_test_results.log
       
-
-      - name: Archive Test Report
+      - name: Archive Pytest Report
         uses: actions/upload-artifact@v3
         with:
-          name: selenium-test-report
-          path: report.html
-
-      - name: Archive Test Results
+          name: pytest-results
+          path: pytest_results.log
+      
+      - name: Archive Python Test Results
         uses: actions/upload-artifact@v3
         with:
-          name: test-results
-          path: test_results.log
+          name: python-test-results
+          path: python_test_results.log
 
       - name: Check if tests passed
         run: |
-          if grep -q "FAILED" test_results.log; then
-            echo "Some tests failed."
-            exit 1  # Ensure the workflow fails if any test fails
+          if grep -q "FAILED" pytest_results.log || grep -q "FAILED" python_test_results.log; then
+           echo "Some tests failed."
+           exit 1  # Ensure the workflow fails if any test fails
           else
-            echo "All tests passed."
+           echo "All tests passed."
           fi
       
+     
       - name: Make deploy script executable
         run: chmod +x deploy_script.sh
       
