updated Fully

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,14 +29,18 @@ jobs:
         with:
           python-version: '3.9'  # Specify the Python version to use
 
+      - name: List files to verify requirements.txt path
+        run: ls -la
+  
       - name: Check for requirements.txt
         run: |
-            if [ ! -f "config/requirements.txt" ]; then echo "requirements.txt not found!"; exit 1; fi
-  
-      - name: Install dependencies
-        run: |
-            python -m pip install --upgrade pip
-            pip install --no-cache-dir -r config/requirements.txt  # Adjusted path for requirements.txt inside a folder
+            if [ ! -f "requirements.txt" ]; then echo "requirements.txt not found!"; exit 1; fi
+
+      - name: Upgrade pip
+        run: python -m pip install --upgrade pip
+
+      - name: Install dependencies without cache
+        run: pip install --no-cache-dir -r requirements.txt
   
      
       - name: Check Docker version
