updated

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -67,21 +67,44 @@ jobs:
           asset_content_type: application/x-xz
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      - name: Run pytest with HTML report
+          
+      - name: Run Selenium tests and display results
         run: |
-            pytest --html=report.html --self-contained-html  # Run pytest and generate report
-    
-      - name: Upload HTML report as artifact
+            pytest google.py > pytest_results.log || exit 0  # Run google.py tests
+            cat pytest_results.log    # Display google.py results for debugging
+  
+            pytest test.py > pytest_test_results.log || exit 0  # Run test.py tests
+            cat pytest_test_results.log    # Display test.py results for debugging
+  
+        
+      - name: Archive Pytest Report
         uses: actions/upload-artifact@v3
         with:
-            name: pytest-report  # The name of the artifact
-            path: report.html  # Path to the HTML report file
-    
-      - name: Display test results in GitHub UI
+            name: pytest-results
+            path: pytest_results.log
+        
+      - name: Archive Pytest Test Results
         uses: actions/upload-artifact@v3
         with:
-            name: pytest-report
-            path: report.html  # Upload the generated HTML report as an artifact
+            name: pytest-test-results
+            path: pytest_test_results.log
+        
+      - name: Archive HTML Test Report
+        uses: actions/upload-artifact@v3
+        with:
+            name: selenium-test-report
+            path: report.html
+        
+      - name: Check if tests passed
+        run: |
+            if grep -q "FAILED" pytest_results.log || grep -q "FAILED" pytest_test_results.log; then
+              echo "Some tests failed."
+              exit 1  # Ensure the workflow fails if any test fails
+            else
+              echo "All tests passed."
+            fi
+        
+     
       - name: Make deploy script executable
         run: chmod +x deploy_script.sh
       
